function spd = importSPD1ft
%IMPORTFILE Import data from a spreadsheet
%   DATA = IMPORTFILE(FILE) reads all numeric data from the first worksheet
%   in the Microsoft Excel spreadsheet file named FILE and returns the
%   numeric data.
%
%   DATA = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE(FILE,SHEET,RANGE) reads from the specified worksheet
%   and from the specified RANGE. Specify RANGE using the syntax
%   'C1:C2',where C1 and C2 are opposing corners of the region.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   SPD = importfile('SPD.xlsx','Spectral','A1:KI421');
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2013/12/17 15:08:52

%% Input handling

workbookFile = '\\root\projects\NASA-Review\SPD1ft.xlsx';

% If no sheet is specified, read first sheet
sheetName = 1;

% If no range is specified, read all data
range = '';

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, range);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

samples = size(data,2) - 1;

spd = cell(1,samples);

for i1 = 1:samples
    spd{i1} = [data(:,1),data(:,i1+1)];
end

end

